version: "3.9"
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: go_service
    ports:
      - 5000:5000

    

      
